In [9]:
import pandas as pd

In [11]:
#Steps to make the data messy.
#The original dataset is pretty clean, to practice the data cleaning steps, we can make the data a bit messy using these steps

hotel_bookings_clean = pd.read_csv('../Data/hotel_bookings.csv')

hotel_bookings_messy = hotel_bookings_clean.copy()

#Change some of the int dtypes to floats and some to strings
hotel_bookings_messy['lead_time'] = hotel_bookings_messy['lead_time'].astype('str')

#Combine arrival date and month and drop separate columns
hotel_bookings_messy['arrival_date'] = hotel_bookings_messy['arrival_date_month'] + "-" + hotel_bookings_messy['arrival_date_year'].astype('str')
hotel_bookings_messy.drop(columns = ['arrival_date_month', 'arrival_date_year'], inplace=True)

column_to_move = hotel_bookings_messy.pop('arrival_date')
hotel_bookings_messy.insert(3, 'arrival_date', column_to_move)

#Add random special characters
indexes = hotel_bookings_messy['hotel'].sample(10000).index.tolist()
character_to_add = '^'
hotel_bookings_messy.loc[indexes, 'hotel'] = character_to_add + hotel_bookings_messy['hotel']


indexes = hotel_bookings_messy['hotel'].sample(10000).index.tolist()
character_to_add = '**'
hotel_bookings_messy.loc[indexes, 'hotel'] = hotel_bookings_messy['hotel'] + character_to_add 

indexes = hotel_bookings_messy['hotel'].sample(10000).index.tolist()
character_to_add = '\n'
hotel_bookings_messy.loc[indexes, 'hotel'] = hotel_bookings_messy['hotel'] + character_to_add

In [12]:
#Save to csv to read in the next step, comment out once you do this
hotel_bookings_messy.to_csv('hotel_bookings_messy.csv')

In [13]:
# #Read the dataset
hotel_bookings = pd.read_csv('hotel_bookings_messy.csv')

In [14]:
# #first look of the dataset
hotel_bookings

,Unnamed: 0,hotel,is_canceled,lead_time,arrival_date,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,0,^Resort Hotel,0,342,July-2015,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,1,Resort Hotel,0,737,July-2015,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,2,^Resort Hotel,0,7,July-2015,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,3,Resort Hotel\n,0,13,July-2015,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,4,Resort Hotel,0,14,July-2015,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,119385,City Hotel**,0,23,August-2017,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,119386,City Hotel,0,102,August-2017,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,119387,City Hotel,0,34,August-2017,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,119388,City Hotel\n,0,109,August-2017,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,119389,City Hotel,0,205,August-2017,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [15]:
hotel_bookings.columns

Index(['Unnamed: 0', 'hotel', 'is_canceled', 'lead_time', 'arrival_date',
       'arrival_date_week_number', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

In [16]:
#drop/rename column
hotel_bookings.drop(columns=['Unnamed: 0'],inplace=True)
hotel_bookings.rename({'adults':'num_adults','children': 'num_children','babies': 'num_babies'}, axis=1,inplace=True)
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,num_children,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,^Resort Hotel,0,342,July-2015,27,1,0,0,2,0.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,July-2015,27,1,0,0,2,0.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,^Resort Hotel,0,7,July-2015,27,1,0,1,1,0.0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel\n,0,13,July-2015,27,1,0,1,1,0.0,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,July-2015,27,1,0,2,2,0.0,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [17]:
#NaNs
hotel_bookings.isnull().sum()*100/len(hotel_bookings)

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date                       0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
num_adults                         0.000000
num_children                       0.003350
num_babies                         0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [18]:
hotel_bookings['agent'].unique()
hotel_bookings[hotel_bookings['agent']==5]

#hotel_bookings['agent'].fillna(-1,inplace=True)
hotel_bookings.fillna({'agent': -1}, inplace=True)
hotel_bookings[hotel_bookings['country'].isna()][['hotel','is_canceled','country']]
hotel_bookings.fillna({'country':'Unknown'},inplace=True)
hotel_bookings.dropna(subset=['num_children'],inplace=True)

In [19]:
#Drop company
hotel_bookings.drop(columns=['company'], inplace=True)

In [20]:
#Check column data types
hotel_bookings.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date                          str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
num_children                      float64
num_babies                          int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [21]:
hotel_bookings = hotel_bookings.astype({'is_canceled':'boolean', 'is_repeated_guest': 'boolean','num_children':'int'})
hotel_bookings.dtypes

hotel                                 str
is_canceled                       boolean
lead_time                           int64
arrival_date                          str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
num_adults                          int64
num_children                        int64
num_babies                          int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                 boolean
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [24]:
#Bin columns
hotel_bookings['lead_time'].unique()
hotel_bookings['lead_time'].describe()

bins = [0, 100, 200, 300, 400, 500, 600, 700, 800]
labels = ['0-100','101-200','201-300','301-400','401-500','501-600','601-700','701-800']
hotel_bookings['lead_time_binned'] = pd.cut(hotel_bookings['lead_time'],bins=bins,labels=labels)
hotel_bookings[['lead_time','lead_time_binned']]

        lead_time lead_time_binned
0             342          301-400
1             737          701-800
2               7            0-100
3              13            0-100
4              14            0-100
...           ...              ...
119385         23            0-100
119386        102          101-200
119387         34            0-100
119388        109          101-200
119389        205          201-300

[119386 rows x 2 columns]

In [25]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,num_children,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_binned
0,^Resort Hotel,False,342,July-2015,27,1,0,0,2,0,...,No Deposit,-1.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,301-400
1,Resort Hotel,False,737,July-2015,27,1,0,0,2,0,...,No Deposit,-1.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,701-800
2,^Resort Hotel,False,7,July-2015,27,1,0,1,1,0,...,No Deposit,-1.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
3,Resort Hotel\n,False,13,July-2015,27,1,0,1,1,0,...,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
4,Resort Hotel,False,14,July-2015,27,1,0,2,2,0,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,0-100

In [30]:
#separate arrival_date column
hotel_bookings['arrival_date_month'] = hotel_bookings['arrival_date'].str.split('-', expand=True)[0]
hotel_bookings['arrival_date_year'] = hotel_bookings['arrival_date'].str.split('-', expand=True)[1]

column_to_move = hotel_bookings.pop('arrival_date_month')
hotel_bookings.insert(4,'arrival_date_month',column_to_move)
hotel_bookings.head()

column_to_move = hotel_bookings.pop('arrival_date_year')
hotel_bookings.insert(5,'arrival_date_year',column_to_move)
hotel_bookings.head()

hotel_bookings.drop('arrival_date', axis=1, inplace=True)
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_binned
0,^Resort Hotel,False,342,July,2015,27,1,0,0,2,...,No Deposit,-1.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,301-400
1,Resort Hotel,False,737,July,2015,27,1,0,0,2,...,No Deposit,-1.0,0,Transient,0.0,0,0,Check-Out,2015-07-01,701-800
2,^Resort Hotel,False,7,July,2015,27,1,0,1,1,...,No Deposit,-1.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
3,Resort Hotel\n,False,13,July,2015,27,1,0,1,1,...,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
4,Resort Hotel,False,14,July,2015,27,1,0,2,2,...,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,0-100

In [ ]:
#String Cleaning